---
name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip wheel
      - run: >-
          pip install bandit black codespell flake8 flake8-2020flake8-bugbear
          flake8-comprehensions isort mypy pytest pyupgrade safety
      # Skipping rules that would block the flow at this moment
      - run: bandit --recursive --skip B101,B105,B110,B307,B310,B311 .
      - run: black --check . || true
      # Skipping codespell because of french comments
      # - run: codespell --ignore-words-list="hass"
      # Ignoring rules to avoid blocking, and complexity level too high
      - run: >-
          flake8 . --count
          --ignore E401,F401,W503,F841,E266,E402,E722,C416,B001,B008
          --max-complexity=35 --max-line-length=184 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements.txt || pip install --editable . || true
      - run: mkdir --parents --verbose .mypy_cache
      - run: >-
          mypy --ignore-missing-imports --install-types --non-interactive . ||
          true
      - run: pytest . || true
      #- run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check -i 43975
